# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ee5ff54a8b6743ac93a04ecad53936e267834d2115bf25b86b26acdb0f20eeaeda9c8581328fb6fcf014989230331378ae18c7ec417a17d8bd9105e631a60d

test:
  secret_key_base: 59161b616d49d56484d33783e13742fff625b8cb6643cd8b3f9302ee4be17d0d600870f1a23f3d35bd0081d958a1c2f3011ccbdbde718d14fc137ae6c74ead0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
